version: "3.9"

services:
  nginx:
    container_name: crud-nginx
    image: nginx:1.23.1
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  php:
    container_name: crud-php
    build: ./docker/php/
    working_dir: /var/www
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www
    depends_on:
      - mariadb

  mariadb:
    container_name: crud-mariadb
    image: mariadb:10.9
    env_file:
        - ./.env
    volumes:
        - ./docker/mysql/data/mariadb:/var/lib/mysql
    ports:
        - 3307:3306

  app:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:5.0.4
    container_name: crud-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 100000000
